language: php

matrix:
  fast_finish: true
  include:
  - php: 7.2
    env: OP=install
  - php: 7.0.8
    env: OP="update --prefer-lowest"

sudo: false

before_script:
  - travis_retry composer $OP --prefer-source --no-interaction

script:
  - composer unit
